SUPABASE_URL="https://ehweosvfmvuotxoziinl.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVod2Vvc3ZmbXZ1b3R4b3ppaW5sIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzY3NTIxNCwiZXhwIjoyMDY5MjUxMjE0fQ.f73Z0Kd8iV4-FOlcxMc8RX3zyDH2E7B3PEkDGZYDvpY"
